export const PermissionKeys = {
  dashboardView: "dashboard.view",
  usersView: "users.view",
  usersCreate: "users.create",
  usersUpdate: "users.update",
  usersDelete: "users.delete",
  permissionsView: "permissions.view",
  leadsView: "leads.view",
  leadsCreate: "leads.create",
  leadsUpdate: "leads.update",
  leadsDelete: "leads.delete",
  tasksView: "tasks.view",
  tasksCreate: "tasks.create",
  tasksUpdate: "tasks.update",
  tasksDelete: "tasks.delete",
  reportsView: "reports.view",
  auditView: "audit.view",
  settingsView: "settings.view",
  customerPortalView: "customer.portal.view",
} as const;
